from rtac.trainers.train_melgan import MelganTrainer, collater
from rtac.trainers.train_multiband_melgan import MultiBandMelganTrainer
from rtac.trainers.base_multireader import MultiReaderBaseTrainer